### ISSUE TITLE
[Question] Is it possible to wrap the contents with a template from a file

### ISSUE THREAD

**Issue by danielpacak** [RReverser/gulp-wrap-js#11]
The `gulp-wrap` has an option to load a template from file and allows one to pass some data/variables to the template. Simply put, how can I migrate from `gulp-wrap` to `gulp-wrap-js` the following gulp config:

``` js
gulp.task('scripts.min', function () {
    return gulp.src(paths.scripts)
        .pipe(sourcemaps.init())
            .pipe(concat('sc-embedded-database.min.js'))
            .pipe(wrap({src: 'gulp/wrap.template.iife'}))
            .pipe(uglify())
            .pipe(wrap({src: 'gulp/wrap.template.banner'}, {version: version}))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(paths.dist))
});
```

where `gulp/wrap.template.iife` contains:

```
(function(window, angular, undefined) {'use strict';
<%= contents %>
})(window, window.angular);
```

and `gulp/wrap.template.banner` contains:

```
/**
 * @license sc-embedded-database v<%= version %>
 * (c) 2014-2015 SOFTWARE CLINIC Pacak Daniel
 * License: MIT
 */
<%= contents %>
```

**Comment by RReverser** [comment]
As for now, you can just read template from file using `fs.readFileSync` once in main script body and pass it as string whenever gulp task requires that.

**Comment by danielpacak** [comment]
All right; thanks for a prompt reply.
