### ISSUE TITLE
Does not work as expected

### ISSUE THREAD

**Issue by oliversalzburg** [RReverser/gulp-wrap-js#12]
I used this plugin in our build. Even though it claims to work with source maps, I was unable to use breakpoints properly in our code as the line numbers were off by approximately 2 lines.

I used to wrap with: `.pipe( wrapJs( "(function() {\n\"use strict\";\n%= body %}());" ) )`
Even removing the `\n` from that template seemed to make no difference.

**Comment by RReverser** [comment]
Well, I don't see your full pipeline. Do you have any other tools there? Did you use `gulp-sourcemaps` as described? I need more context to be able to help you with your issue :)

**Comment by oliversalzburg** [comment]
Here's an example of a complete pipeline:

``` js
gulp.task( "js:user", [ "version" ], () => {
    return gulp.src( [ config.input.js( "application/**/*.js" ),
                       config.input.js( "application/*.js" ) ], {
            base : __dirname
        } )
        .pipe( plumber() )
        .pipe( cache( "js:user" ) )
        .pipe( jshint() )
        .pipe( jshint.reporter( stylish ) )
        .pipe( jsValidate() )
        .pipe( ngAnnotate() )
        .pipe( wrapJs( "(function() {\n\"use strict\";\n%= body %}());" ) )
        .pipe( remember( "js:user" ) )
        .pipe( order() )
        .pipe( sourcemaps.init() )
        .pipe( concat( `${slug( application.name )}.user.js` ) )
        .pipe( sourcemaps.write( "maps" ) )
        .pipe( gulp.dest( config.output.js() ) )
        .pipe( ignore.exclude( /maps/ ) )
        .pipe( uglify() )
        .pipe( rename( {
            extname : ".min.js"
        } ) )
        .pipe( sourcemaps.write( "maps" ) )
        .pipe( gulp.dest( config.output.js() ) );
} );
```

I was only testing with the unminified version. So the minification part should hopefully not be relevant.

I am now using the following pipeline instead:

``` js
gulp.task( "js:user", [ "version" ], () => {
    return gulp.src( [ config.input.js( "application/**/*.js" ),
                       config.input.js( "application/*.js" ) ], {
            base : __dirname
        } )
        .pipe( plumber() )
        .pipe( cache( "js:user" ) )
        .pipe( jshint() )
        .pipe( jshint.reporter( stylish ) )
        .pipe( jsValidate() )
        .pipe( sourcemaps.init() )
        .pipe( wrap( "(function() {\"use strict\";<%= contents %>}());" ) )
        .pipe( ngAnnotate() )
        .pipe( remember( "js:user" ) )
        .pipe( order() )
        .pipe( concat( `${slug( application.name )}.user.js` ) )
        .pipe( sourcemaps.write( "maps" ) )
        .pipe( gulp.dest( config.output.js() ) )
        .pipe( ignore.exclude( /maps/ ) )
        .pipe( uglify() )
        .pipe( rename( {
            extname : ".min.js"
        } ) )
        .pipe( sourcemaps.write( "maps" ) )
        .pipe( gulp.dest( config.output.js() ) );
} );
```

**Comment by oliversalzburg** [comment]
Sorry for the editing, I had grabbed the wrong version from VCS on my initial post.

The first version is what I used to use, because I couldn't get wrap-js to work right _with_ source maps. So that version uses wrap-js _before_ source maps are initialized. This works, but you don't see your original input in the debugger.

When you start moving relevant tasks, like ngAnnotate and wrap, into the source maps generation part, the output will no longer work right. In fact, I was able to move everything into the source maps generation part, except for wrap-js.

So, ultimately, I removed wrap-js and went with the second version.

**Comment by RReverser** [comment]
> When you start moving relevant tasks, like ngAnnotate and wrap, into the source maps generation part, the output will no longer work right. 

Well, as far as I understand from https://www.npmjs.com/package/gulp-ng-annotate, it doesn't support gulp-sourcemaps (which in fact any plugins that perform JS transformation should support), so pipeline breaks as actual code and source maps become out-of-sync. Minification should be also part of that pipeline btw.

**Comment by oliversalzburg** [comment]
Minification is part of the pipeline. I write a second set of maps after minification.

What you're saying regarding ng-annotate makes sense, but it just doesn't match my results, or I'm not understanding all the factors at play here.

Taken my original pipeline, when I remove ng-annotate from it, like so:

``` js
gulp.task( "js:user", [ "version" ], () => {
    return gulp.src( [ config.input.js( "application/**/*.js" ),
                       config.input.js( "application/*.js" ) ], {
            base : __dirname
        } )
        .pipe( plumber() )
        .pipe( cache( "js:user" ) )
        .pipe( jshint() )
        .pipe( jshint.reporter( stylish ) )
        .pipe( jsValidate() )
        .pipe( sourcemaps.init() )
        //.pipe( ngAnnotate() )
        .pipe( wrapJs( "(function() {\n\"use strict\";\n%= body %}());" ) )
        .pipe( remember( "js:user" ) )
        .pipe( order() )
        .pipe( concat( `${slug( application.name )}.user.js` ) )
        .pipe( sourcemaps.write( "maps" ) )
        .pipe( gulp.dest( config.output.js() ) )
        .pipe( ignore.exclude( /maps/ ) )
        .pipe( uglify() )
        .pipe( rename( {
            extname : ".min.js"
        } ) )
        .pipe( sourcemaps.write( "maps" ) )
        .pipe( gulp.dest( config.output.js() ) );
} );
```

I will still see mismatching breakpoint placement in the debugger.

However, if I remove wrap-js like so:

``` js
gulp.task( "js:user", [ "version" ], () => {
    return gulp.src( [ config.input.js( "application/**/*.js" ),
                       config.input.js( "application/*.js" ) ], {
            base : __dirname
        } )
        .pipe( plumber() )
        .pipe( cache( "js:user" ) )
        .pipe( jshint() )
        .pipe( jshint.reporter( stylish ) )
        .pipe( jsValidate() )
        .pipe( sourcemaps.init() )
        .pipe( ngAnnotate() )
        //.pipe( wrapJs( "(function() {\n\"use strict\";\n%= body %}());" ) )
        .pipe( remember( "js:user" ) )
        .pipe( order() )
        .pipe( concat( `${slug( application.name )}.user.js` ) )
        .pipe( sourcemaps.write( "maps" ) )
        .pipe( gulp.dest( config.output.js() ) )
        .pipe( ignore.exclude( /maps/ ) )
        .pipe( uglify() )
        .pipe( rename( {
            extname : ".min.js"
        } ) )
        .pipe( sourcemaps.write( "maps" ) )
        .pipe( gulp.dest( config.output.js() ) );
} );
```

Everything is working as expected.

**Comment by RReverser** [comment]
Yeah, that's weird. You have lots of plugins there though, I can't tell which one conflicts with wrapJS...

**Comment by oliversalzburg** [comment]
Well, when I remove everything except wrap-js, I don't see any problem either :(

Oh well, as you just said, it's probably a conflict with another plugin that doesn't properly support source maps or something else.

Thanks anyway.
